export const getIsLoading = ({ user }) => user.isLoading;
export const getId = ({ user }) => user.id;
export const getKarma = ({ user }) => user.karma;
export const getCreated = ({ user }) => user.created;
export const getSubmitted = ({ user }) => user.submitted;
export const getAbout = ({ user }) => user.about;
export const getSubmissions = ({ user }) => user.submissions;
export const getIsLoadingSubmissions = ({ user }) => user.isLoadingSubmissions;
export const getError = ({ user }) => user.error;
